// libs
import { v4 as uuid } from "uuid";

// internals
import { Item, Survivor } from "./types";

export const POSSIBLE_ITEMS: Item[] = [
  {
    id: uuid(),
    label: "water",
    worth: 4,
  },
  {
    id: uuid(),
    label: "food",
    worth: 3,
  },
  {
    id: uuid(),
    label: "medication",
    worth: 2,
  },
  {
    id: uuid(),
    label: "ammunition",
    worth: 1,
  },
];

export const MOCK_SURVIVORS: Survivor[] = [
  {
    id: uuid(),
    name: "John Doe",
    age: 30,
    gender: "m",
    lastLocation: { id: "loc1", lat: "34.0522", lon: "-118.2437" },
    inventory: [POSSIBLE_ITEMS[0].id, POSSIBLE_ITEMS[1].id],
    infectionReports: [],
  },
  {
    id: uuid(),
    name: "Jane Smith",
    age: 25,
    gender: "f",
    lastLocation: { id: "loc2", lat: "40.7128", lon: "-74.0060" },
    inventory: [POSSIBLE_ITEMS[2].id, POSSIBLE_ITEMS[3].id],
    infectionReports: [],
  },
  {
    id: uuid(),
    name: "Alice Johnson",
    age: 28,
    gender: "f",
    lastLocation: { id: "loc3", lat: "37.7749", lon: "-122.4194" },
    inventory: [POSSIBLE_ITEMS[1].id, POSSIBLE_ITEMS[3].id],
    infectionReports: [],
  },
  {
    id: uuid(),
    name: "Bob Brown",
    age: 35,
    gender: "m",
    lastLocation: { id: "loc4", lat: "51.5074", lon: "-0.1278" },
    inventory: [POSSIBLE_ITEMS[0].id, POSSIBLE_ITEMS[2].id],
    infectionReports: [],
  },
  {
    id: uuid(),
    name: "Charlie Davis",
    age: 40,
    gender: "m",
    lastLocation: { id: "loc5", lat: "48.8566", lon: "2.3522" },
    inventory: [POSSIBLE_ITEMS[1].id, POSSIBLE_ITEMS[2].id],
    infectionReports: [],
  },
  {
    id: uuid(),
    name: "Diana Evans",
    age: 22,
    gender: "f",
    lastLocation: { id: "loc6", lat: "35.6895", lon: "139.6917" },
    inventory: [POSSIBLE_ITEMS[0].id, POSSIBLE_ITEMS[3].id],
    infectionReports: [],
  },
  {
    id: uuid(),
    name: "Ethan Foster",
    age: 27,
    gender: "m",
    lastLocation: { id: "loc7", lat: "55.7558", lon: "37.6173" },
    inventory: [POSSIBLE_ITEMS[1].id, POSSIBLE_ITEMS[2].id],
    infectionReports: [],
  },
  {
    id: uuid(),
    name: "Fiona Green",
    age: 32,
    gender: "f",
    lastLocation: { id: "loc8", lat: "39.9042", lon: "116.4074" },
    inventory: [POSSIBLE_ITEMS[0].id, POSSIBLE_ITEMS[1].id],
    infectionReports: [],
  },
  {
    id: uuid(),
    name: "George Harris",
    age: 29,
    gender: "m",
    lastLocation: { id: "loc9", lat: "34.0522", lon: "-118.2437" },
    inventory: [POSSIBLE_ITEMS[2].id, POSSIBLE_ITEMS[3].id],
    infectionReports: [],
  },
  {
    id: uuid(),
    name: "Hannah Irving",
    age: 24,
    gender: "f",
    lastLocation: { id: "loc10", lat: "40.7128", lon: "-74.0060" },
    inventory: [POSSIBLE_ITEMS[1].id, POSSIBLE_ITEMS[3].id],
    infectionReports: [],
  },
  {
    id: uuid(),
    name: "Ian Jackson",
    age: 31,
    gender: "m",
    lastLocation: { id: "loc11", lat: "37.7749", lon: "-122.4194" },
    inventory: [POSSIBLE_ITEMS[0].id, POSSIBLE_ITEMS[2].id],
    infectionReports: [],
  },
  {
    id: uuid(),
    name: "Julia King",
    age: 26,
    gender: "f",
    lastLocation: { id: "loc12", lat: "51.5074", lon: "-0.1278" },
    inventory: [POSSIBLE_ITEMS[1].id, POSSIBLE_ITEMS[2].id],
    infectionReports: [],
  },
  {
    id: uuid(),
    name: "Kevin Lewis",
    age: 33,
    gender: "m",
    lastLocation: { id: "loc13", lat: "48.8566", lon: "2.3522" },
    inventory: [POSSIBLE_ITEMS[0].id, POSSIBLE_ITEMS[3].id],
    infectionReports: [],
  },
  {
    id: uuid(),
    name: "Laura Martinez",
    age: 21,
    gender: "f",
    lastLocation: { id: "loc14", lat: "35.6895", lon: "139.6917" },
    inventory: [POSSIBLE_ITEMS[1].id, POSSIBLE_ITEMS[2].id],
    infectionReports: [],
  },
  {
    id: uuid(),
    name: "Michael Nelson",
    age: 34,
    gender: "m",
    lastLocation: { id: "loc15", lat: "55.7558", lon: "37.6173" },
    inventory: [POSSIBLE_ITEMS[0].id, POSSIBLE_ITEMS[1].id],
    infectionReports: [],
  },
  {
    id: uuid(),
    name: "Nina Owens",
    age: 28,
    gender: "f",
    lastLocation: { id: "loc16", lat: "39.9042", lon: "116.4074" },
    inventory: [POSSIBLE_ITEMS[2].id, POSSIBLE_ITEMS[3].id],
    infectionReports: [],
  },
  {
    id: uuid(),
    name: "Oscar Perez",
    age: 30,
    gender: "m",
    lastLocation: { id: "loc17", lat: "34.0522", lon: "-118.2437" },
    inventory: [POSSIBLE_ITEMS[1].id, POSSIBLE_ITEMS[3].id],
    infectionReports: [],
  },
  {
    id: uuid(),
    name: "Paula Quinn",
    age: 27,
    gender: "f",
    lastLocation: { id: "loc18", lat: "40.7128", lon: "-74.0060" },
    inventory: [POSSIBLE_ITEMS[0].id, POSSIBLE_ITEMS[2].id],
    infectionReports: [],
  },
  {
    id: uuid(),
    name: "Quincy Roberts",
    age: 32,
    gender: "m",
    lastLocation: { id: "loc19", lat: "37.7749", lon: "-122.4194" },
    inventory: [POSSIBLE_ITEMS[1].id, POSSIBLE_ITEMS[2].id],
    infectionReports: [
      {
        id: "ir1",
        created: new Date(),
        reporter: "17",
      },
    ],
  },
  {
    id: uuid(),
    name: "Rachel Scott",
    age: 25,
    gender: "f",
    lastLocation: { id: "loc20", lat: "51.5074", lon: "-0.1278" },
    inventory: [POSSIBLE_ITEMS[0].id, POSSIBLE_ITEMS[3].id],
    infectionReports: [],
  },
];
